--table tasks
CREATE TABLE tasks (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(300),
  done BOOL NOT NULL DEFAULT 0, 
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);